import './globals.css';
import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import React from 'react';
import LayoutHeader from "@/components/layout.header";
import LayoutFooter from "@/components/layout.footer";
import styles from '../../styles/layout.module.scss'
import {AuthContextProvider} from "@/context/AuthContext";

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={inter.className}>
        <AuthContextProvider>
          <LayoutHeader/>
          <div className={styles.container}>
            {children}
          </div>
          <LayoutFooter/>
        </AuthContextProvider>
      </body>
    </html>
  );
}
